Repository FuelRats/pipsqueak3, pull requests merged in 2019-03, with the labels that each got.

#120 parallelize build system
  .circleci/config.yml
Labels: CI change

#119 [SPARK-110] contributing update.
  CONTRIBUTING.md
Labels: Documentation, Team Decision

#118 [SPARK-48] Unit Tests for mechaclient.py
  pytest.ini
  tests/test_mechaclient.py
Labels: Feature

#124 [SPARK-119] Update psycopg2, switch to binary version.
  Pipfile
  Pipfile.lock
Labels: Dependency change

#125 [SPARK-120] Move Galaxy's fixture into a position where all modules can use it
  tests/conftest.py
  tests/galaxy/galaxy_fx.py
Labels: Refactor

#131 [Spark 127] TOML based configuration files
  Pipfile
  Pipfile.lock
  config.py
  config/config.template.json
  config/config.template.toml
  config/configuration.md
  config/testing.toml
  src/packages/cli_manager/cli_manager.py
  tests/conftest.py
  tools/json_to_toml.py
Labels: Dependency change, Documentation, Feature, Refactor
