Repository FuelRats/pipsqueak3, pull requests merged in 2019-04, with the labels that each got.

#126 [SPARK-122] Adjust Galaxy's search parameters to use API indexes
  src/packages/galaxy/galaxy.py
  tests/galaxy/galaxy_fx.py
Labels: Refactor

#133 [SPARK-133] Restructure test folder
  .circleci/config.yml
  pytest.ini
  tests/conftest.py
  tests/fixtures/galaxy_fx.py
  tests/fixtures/mock_bot.py
  tests/fixtures/mock_callables.py
  tests/integration/.keep
  tests/offline_mode/__init__.py
  tests/unit/__init__.py
  tests/unit/test_autocorrect.py
  tests/unit/test_context.py
  tests/unit/test_database_manager.py
  tests/unit/test_epic.py
  tests/unit/test_fact.py
  tests/unit/test_fact_manager.py
  tests/unit/test_galaxy.py
  tests/unit/test_graceful_error.py
  tests/unit/test_logging.py
  tests/unit/test_mark_for_deletion.py
  tests/unit/test_mechaclient.py
  tests/unit/test_offline_abc.py
  tests/unit/test_permissions.py
  tests/unit/test_quotes.py
  tests/unit/test_rat_board.py
  tests/unit/test_rat_cache.py
  tests/unit/test_rat_command.py
  tests/unit/test_ratlib.py
  tests/unit/test_ratmama.py
  tests/unit/test_rats.py
  tests/unit/test_rescue.py
  tests/unit/test_rules.py
  tests/unit/test_setup.py
  tests/unit/test_user.py
Labels: CI change, Refactor

#130 [SPARK-126] Add a Mecha3 smoke test
  .circleci/config.yml
  config/circle.toml
Labels: CI change

#129 [SPARK-124] Add a retry handler to Galaxy's _call
  src/packages/galaxy/galaxy.py
  tests/fixtures/galaxy_fx.py
  tests/unit/test_galaxy.py
Labels: Feature, Refactor

#134 [SPARK-134] Fix DBM's AttributeError
  src/packages/database/database_manager.py
Labels: Bug fix

#135 SPARK-136 Part 1.
  tests/unit/test_ratmama.py
Labels: Bug

#138 CodeCov reconfiguration
  .circleci/config.yml
  .codecov.yml
Labels: CI change

#136 User Dataclass
  src/packages/user/user.py
Labels: Feature, Refactor

#137 [SPARK-136] Refactor "RatMama" test suite
  config/testing.toml
  src/packages/ratmama/ratmama_parser.py
  tests/fixtures/mock_bot.py
  tests/unit/test_ratmama.py
Labels: Refactor

#141 Refactored `..context._split_message` to be less hacky
  src/packages/context/context.py
  tests/unit/test_context.py
Labels: Refactor

#142 Update dependencies.
  Pipfile.lock
Labels: Bug, Dependency change
