Repository FuelRats/pipsqueak3, pull requests merged in 2019-07, with the labels that each got.

#151 [CI] pin OS distribution for testing
  .circleci/config.yml
Labels: CI change, Dependency change

#152 Merge testing config files
  .circleci/config.yml
  config/circle.toml
  config/testing.toml
Labels: CI change

#150 [SPARK-148] Give Galaxy its own configuration value
  config/config.template.toml
  config/testing.toml
  src/packages/galaxy/galaxy.py
Labels: Refactor
