Repository FuelRats/pipsqueak3, pull requests merged in 2020-10, with the labels that each got.

#203 [SPARK-231] Purge Codecov
  .circleci/config.yml
  .codecov.yml
  CONTRIBUTING.md
  README.md
Labels: CI change, Policy change

#205 [SPARK-165] Feature/ratmama announce process distance
  src/packages/ratmama/ratmama_parser.py
  tests/conftest.py
  tests/fixtures/galaxy_fx.py
  tests/unit/test_ratmama.py
Labels: Feature

#204 Doc/simplify infrastructure deployment
  .dockerignore
  .gitignore
  Docker.md
  Dockerfile
  README.md
  config/config.template.toml
  docker-compose.template.yml
  docker-compose.yml
  initdb.sql
Labels: Documentation, Feature

#201 Update cheese list
  src/packages/graceful_errors/graceful_errors.py
Labels: Feature

#206 [SPARK-217|SPARK-208] Implemented Drill Mode + config overhaul
  src/__main__.py
  src/commands/case_management.py
  src/config/_parser.py
  src/config/_spec.py
  src/config/datamodel/__init__.py
  src/config/datamodel/api.py
  src/config/datamodel/auth.py
  src/config/datamodel/board.py
  src/config/datamodel/commands.py
  src/config/datamodel/database.py
  src/config/datamodel/gelf.py
  src/config/datamodel/irc.py
  src/config/datamodel/permissions.py
  src/config/datamodel/ratmamma.py
  src/config/datamodel/root.py
  src/mechaclient.py
  src/packages/board/board.py
  src/packages/context/context.py
  src/packages/database/database_manager.py
  src/packages/fact_manager/fact_manager.py
  src/packages/fuelrats_api/_base.py
  src/packages/fuelrats_api/v3/interface.py
  src/packages/galaxy/galaxy.py
  src/packages/permissions/permissions.py
  src/packages/ratmama/ratmama_parser.py
  tests/conftest.py
  tests/fixtures/mock_websocket.py
  tests/unit/commands/test_board.py
  tests/unit/test_database_manager.py
  tests/unit/test_mechaclient.py
  tests/unit/test_rat_command.py
Labels: Feature, Refactor

#208 Release 3.2.0
  poetry.lock
  pyproject.toml
Labels: Release
